- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Check AWS Zones
      amazon.aws.aws_az_info:
        region: us-east-1
